import { describe, it, expect, vi } from 'vitest'
import { resolveScript, getConcreteAlgoId } from '@/hooks/resolveScript'
import type { AlgorithmType } from '@/store/algorithmStore'
import type { OperationDef } from '@/presets/operationPresets'
import type { AnimationScript } from '@/types/animation'

function makeAlgo(overrides: Partial<AlgorithmType> & { id: string }): AlgorithmType {
  return {
    name: overrides.id,
    nameEn: overrides.id,
    category: 'sorting',
    difficulty: 'easy',
    hasPreset: false,
    defaultCode: '',
    defaultLanguage: 'python',
    ...overrides,
  } as AlgorithmType
}

const STUB_SCRIPT: AnimationScript = {
  algorithm: 'stub',
  complexity: { time: { best: 'O(1)', average: 'O(1)', worst: 'O(1)' }, space: 'O(1)' },
  initialState: { type: 'array', data: [] },
  steps: [],
}

describe('getConcreteAlgoId', () => {
  it('maps bst + insert → bst_insert', () => {
    expect(getConcreteAlgoId('bst', 'insert')).toBe('bst_insert')
  })
  it('maps linked_list variants', () => {
    expect(getConcreteAlgoId('doubly_linked_list', 'delete')).toBe('linked_list_delete')
  })
  it('maps btree / bplus_tree', () => {
    expect(getConcreteAlgoId('btree', 'search')).toBe('btree_search')
    expect(getConcreteAlgoId('bplus_tree', 'insert')).toBe('bplus_tree_insert')
  })
  it('passes through unrecognized ids', () => {
    expect(getConcreteAlgoId('bubble_sort', 'insert')).toBe('bubble_sort')
  })
})

describe('resolveScript', () => {
  it('operation-generator path: a custom op with a dynamic generator returns a generated script', () => {
    // bst + insert → bst_insert, which is a registered generator.
    const algo = makeAlgo({ id: 'bst', hasPreset: false })
    const script = resolveScript({
      selectedAlgorithm: algo,
      currentOperationId: 'insert',
      operations: undefined,
      parsedInput: () => [8, 3, 10],
      operationParam: '5',
    })
    expect(script).not.toBeNull()
    // Generated by the bst_insert generator, not the static stub.
    expect(script).not.toBe(STUB_SCRIPT)
    expect(Array.isArray(script!.steps)).toBe(true)
  })

  it('op.script fallback: no dynamic generator → returns the static op script', () => {
    // id 'queue' + op 'frobnicate' → getConcreteAlgoId returns 'queue' (no such
    // generator for that key), so it must fall back to the matching op.script.
    const op: OperationDef = {
      id: 'search',
      label: '查找',
      labelEn: 'Search',
      code: { python: '' },
      script: STUB_SCRIPT,
    }
    const algo = makeAlgo({ id: 'some_struct', hasPreset: false })
    const script = resolveScript({
      selectedAlgorithm: algo,
      currentOperationId: 'search',
      operations: [op],
      parsedInput: () => [1, 2, 3],
      operationParam: '5',
    })
    expect(script).toBe(STUB_SCRIPT)
  })

  it('preset-generator path: hasPreset algo with a generator returns a generated script', () => {
    const algo = makeAlgo({ id: 'bubble_sort', hasPreset: true })
    const parsedInput = vi.fn(() => [5, 3, 8, 1])
    const script = resolveScript({
      selectedAlgorithm: algo,
      currentOperationId: '',
      operations: undefined,
      parsedInput,
      operationParam: '5',
    })
    expect(parsedInput).toHaveBeenCalled()
    expect(script).not.toBeNull()
    expect(script!.algorithm).toBe('bubble_sort')
    expect(script!.steps.length).toBeGreaterThan(0)
  })

  it('static-preset fallback: hasPreset, no generator, but a static preset exists', async () => {
    // Mock @/presets so a hasPreset algo with no generator falls back to getPreset.
    vi.resetModules()
    vi.doMock('@/presets', () => ({
      hasGenerator: () => false,
      generatePreset: () => undefined,
      getPreset: (id: string) => (id === '__static_only__' ? STUB_SCRIPT : undefined),
    }))
    const { resolveScript: resolveScriptMocked } = await import('@/hooks/resolveScript')
    const algo = makeAlgo({ id: '__static_only__', hasPreset: true })
    const script = resolveScriptMocked({
      selectedAlgorithm: algo,
      currentOperationId: '',
      operations: undefined,
      parsedInput: () => [1, 2, 3],
      operationParam: '5',
    })
    expect(script).toBe(STUB_SCRIPT)
    vi.doUnmock('@/presets')
    vi.resetModules()
  })

  it('null case: no operation, no preset → null', () => {
    const algo = makeAlgo({ id: '__nothing__', hasPreset: false })
    const script = resolveScript({
      selectedAlgorithm: algo,
      currentOperationId: '',
      operations: undefined,
      parsedInput: () => [1, 2, 3],
      operationParam: '5',
    })
    expect(script).toBeNull()
  })
})
