export { analyzeCode, getApiConfig } from './client'
export type { AIRequestParams, AIResult, ApiConfig, AnalyzeOptions } from './client'
export { buildSystemPrompt, buildUserMessage } from './prompts'
export { parseAIResponse, parseAIResponseDetailed } from './parser'
export type { ParseResult } from './parser'
export { parseInputData } from './input'
export type { ParsedInputData, InputDataKind } from './input'
export { validateAnimationScript, normalizeAnimationScript } from './schema'
export { attemptLocalRepair, buildRepairPrompt } from './repair'
export type { AIErrorReport, AIValidationIssue, AIErrorStage, AIErrorSeverity, AIRepairAttempt } from './errors'
