import type { AnimationScript } from '@/types/animation'

const bubbleSortPreset: AnimationScript = {
  algorithm: 'bubble_sort',
  complexity: {
    time: { best: 'O(n)', average: 'O(n²)', worst: 'O(n²)' },
    space: 'O(1)',
  },
  initialState: {
    type: 'array',
    data: [5, 3, 8, 1, 9, 2],
    labels: ['5', '3', '8', '1', '9', '2'],
  },
  steps: [
    {
      stepId: 1,
      codeLine: 0,
      description: { zh: '第一轮：比较索引 0 和 1', en: 'Pass 1: Compare index 0 and 1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 1, swaps: 0, accesses: 2 },
    },
    {
      stepId: 2,
      codeLine: 2,
      description: { zh: '5 > 3，交换位置', en: '5 > 3, swap them' },
      action: { type: 'swap', targets: [0, 1], color: 'danger' },
      stats: { comparisons: 1, swaps: 0, accesses: 2 },
    },
    {
      stepId: 3,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [3, 5, 8, 1, 9, 2]', en: 'After swap: [3, 5, 8, 1, 9, 2]' },
      action: { type: 'highlight', targets: [0, 1], color: 'success' },
      stats: { comparisons: 1, swaps: 1, accesses: 4 },
    },
    {
      stepId: 4,
      codeLine: 0,
      description: { zh: '比较索引 1 和 2', en: 'Compare index 1 and 2' },
      action: { type: 'compare', targets: [1, 2], color: 'warning' },
      stats: { comparisons: 2, swaps: 1, accesses: 3 },
    },
    {
      stepId: 5,
      codeLine: 2,
      description: { zh: '5 < 8，不需要交换', en: '5 < 8, no swap needed' },
      action: { type: 'highlight', targets: [1, 2], color: 'success' },
      stats: { comparisons: 2, swaps: 1, accesses: 4 },
    },
    {
      stepId: 6,
      codeLine: 0,
      description: { zh: '比较索引 2 和 3', en: 'Compare index 2 and 3' },
      action: { type: 'compare', targets: [2, 3], color: 'warning' },
      stats: { comparisons: 3, swaps: 1, accesses: 4 },
    },
    {
      stepId: 7,
      codeLine: 2,
      description: { zh: '8 > 1，交换位置', en: '8 > 1, swap them' },
      action: { type: 'swap', targets: [2, 3], color: 'danger' },
      stats: { comparisons: 3, swaps: 1, accesses: 4 },
    },
    {
      stepId: 8,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [3, 5, 1, 8, 9, 2]', en: 'After swap: [3, 5, 1, 8, 9, 2]' },
      action: { type: 'highlight', targets: [2, 3], color: 'success' },
      stats: { comparisons: 3, swaps: 2, accesses: 6 },
    },
    {
      stepId: 9,
      codeLine: 0,
      description: { zh: '比较索引 3 和 4', en: 'Compare index 3 and 4' },
      action: { type: 'compare', targets: [3, 4], color: 'warning' },
      stats: { comparisons: 4, swaps: 2, accesses: 5 },
    },
    {
      stepId: 10,
      codeLine: 2,
      description: { zh: '8 < 9，不需要交换', en: '8 < 9, no swap needed' },
      action: { type: 'highlight', targets: [3, 4], color: 'success' },
      stats: { comparisons: 4, swaps: 2, accesses: 6 },
    },
    {
      stepId: 11,
      codeLine: 0,
      description: { zh: '比较索引 4 和 5', en: 'Compare index 4 and 5' },
      action: { type: 'compare', targets: [4, 5], color: 'warning' },
      stats: { comparisons: 5, swaps: 2, accesses: 6 },
    },
    {
      stepId: 12,
      codeLine: 2,
      description: { zh: '9 > 2，交换位置', en: '9 > 2, swap them' },
      action: { type: 'swap', targets: [4, 5], color: 'danger' },
      stats: { comparisons: 5, swaps: 2, accesses: 6 },
    },
    {
      stepId: 13,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [3, 5, 1, 8, 2, 9]', en: 'After swap: [3, 5, 1, 8, 2, 9]' },
      action: { type: 'highlight', targets: [4, 5], color: 'success' },
      stats: { comparisons: 5, swaps: 3, accesses: 8 },
    },
    {
      stepId: 14,
      codeLine: 4,
      description: { zh: '第一轮结束，最大值 9 已就位', en: 'Pass 1 done, max value 9 in place' },
      action: { type: 'mark', targets: [5], color: 'muted' },
      stats: { comparisons: 5, swaps: 3, accesses: 8 },
    },
    {
      stepId: 15,
      codeLine: 0,
      description: { zh: '第二轮：比较索引 0 和 1', en: 'Pass 2: Compare index 0 and 1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 6, swaps: 3, accesses: 9 },
    },
    {
      stepId: 16,
      codeLine: 2,
      description: { zh: '3 < 5，不需要交换', en: '3 < 5, no swap needed' },
      action: { type: 'highlight', targets: [0, 1], color: 'success' },
      stats: { comparisons: 6, swaps: 3, accesses: 10 },
    },
    {
      stepId: 17,
      codeLine: 0,
      description: { zh: '比较索引 1 和 2', en: 'Compare index 1 and 2' },
      action: { type: 'compare', targets: [1, 2], color: 'warning' },
      stats: { comparisons: 7, swaps: 3, accesses: 10 },
    },
    {
      stepId: 18,
      codeLine: 2,
      description: { zh: '5 > 1，交换位置', en: '5 > 1, swap them' },
      action: { type: 'swap', targets: [1, 2], color: 'danger' },
      stats: { comparisons: 7, swaps: 3, accesses: 10 },
    },
    {
      stepId: 19,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [3, 1, 5, 8, 2, 9]', en: 'After swap: [3, 1, 5, 8, 2, 9]' },
      action: { type: 'highlight', targets: [1, 2], color: 'success' },
      stats: { comparisons: 7, swaps: 4, accesses: 12 },
    },
    {
      stepId: 20,
      codeLine: 0,
      description: { zh: '比较索引 2 和 3', en: 'Compare index 2 and 3' },
      action: { type: 'compare', targets: [2, 3], color: 'warning' },
      stats: { comparisons: 8, swaps: 4, accesses: 11 },
    },
    {
      stepId: 21,
      codeLine: 2,
      description: { zh: '5 < 8，不需要交换', en: '5 < 8, no swap needed' },
      action: { type: 'highlight', targets: [2, 3], color: 'success' },
      stats: { comparisons: 8, swaps: 4, accesses: 12 },
    },
    {
      stepId: 22,
      codeLine: 0,
      description: { zh: '比较索引 3 和 4', en: 'Compare index 3 and 4' },
      action: { type: 'compare', targets: [3, 4], color: 'warning' },
      stats: { comparisons: 9, swaps: 4, accesses: 12 },
    },
    {
      stepId: 23,
      codeLine: 2,
      description: { zh: '8 > 2，交换位置', en: '8 > 2, swap them' },
      action: { type: 'swap', targets: [3, 4], color: 'danger' },
      stats: { comparisons: 9, swaps: 4, accesses: 12 },
    },
    {
      stepId: 24,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [3, 1, 5, 2, 8, 9]', en: 'After swap: [3, 1, 5, 2, 8, 9]' },
      action: { type: 'highlight', targets: [3, 4], color: 'success' },
      stats: { comparisons: 9, swaps: 5, accesses: 14 },
    },
    {
      stepId: 25,
      codeLine: 4,
      description: { zh: '第二轮结束，8 已就位', en: 'Pass 2 done, 8 in place' },
      action: { type: 'mark', targets: [4], color: 'muted' },
      stats: { comparisons: 9, swaps: 5, accesses: 14 },
    },
    {
      stepId: 26,
      codeLine: 0,
      description: { zh: '第三轮：比较索引 0 和 1', en: 'Pass 3: Compare index 0 and 1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 10, swaps: 5, accesses: 15 },
    },
    {
      stepId: 27,
      codeLine: 2,
      description: { zh: '3 > 1，交换位置', en: '3 > 1, swap them' },
      action: { type: 'swap', targets: [0, 1], color: 'danger' },
      stats: { comparisons: 10, swaps: 5, accesses: 15 },
    },
    {
      stepId: 28,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [1, 3, 5, 2, 8, 9]', en: 'After swap: [1, 3, 5, 2, 8, 9]' },
      action: { type: 'highlight', targets: [0, 1], color: 'success' },
      stats: { comparisons: 10, swaps: 6, accesses: 17 },
    },
    {
      stepId: 29,
      codeLine: 0,
      description: { zh: '比较索引 1 和 2', en: 'Compare index 1 and 2' },
      action: { type: 'compare', targets: [1, 2], color: 'warning' },
      stats: { comparisons: 11, swaps: 6, accesses: 16 },
    },
    {
      stepId: 30,
      codeLine: 2,
      description: { zh: '3 < 5，不需要交换', en: '3 < 5, no swap needed' },
      action: { type: 'highlight', targets: [1, 2], color: 'success' },
      stats: { comparisons: 11, swaps: 6, accesses: 17 },
    },
    {
      stepId: 31,
      codeLine: 0,
      description: { zh: '比较索引 2 和 3', en: 'Compare index 2 and 3' },
      action: { type: 'compare', targets: [2, 3], color: 'warning' },
      stats: { comparisons: 12, swaps: 6, accesses: 17 },
    },
    {
      stepId: 32,
      codeLine: 2,
      description: { zh: '5 > 2，交换位置', en: '5 > 2, swap them' },
      action: { type: 'swap', targets: [2, 3], color: 'danger' },
      stats: { comparisons: 12, swaps: 6, accesses: 17 },
    },
    {
      stepId: 33,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [1, 3, 2, 5, 8, 9]', en: 'After swap: [1, 3, 2, 5, 8, 9]' },
      action: { type: 'highlight', targets: [2, 3], color: 'success' },
      stats: { comparisons: 12, swaps: 7, accesses: 19 },
    },
    {
      stepId: 34,
      codeLine: 4,
      description: { zh: '第三轮结束，5 已就位', en: 'Pass 3 done, 5 in place' },
      action: { type: 'mark', targets: [3], color: 'muted' },
      stats: { comparisons: 12, swaps: 7, accesses: 19 },
    },
    {
      stepId: 35,
      codeLine: 0,
      description: { zh: '第四轮：比较索引 0 和 1', en: 'Pass 4: Compare index 0 and 1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 13, swaps: 7, accesses: 20 },
    },
    {
      stepId: 36,
      codeLine: 2,
      description: { zh: '1 < 3，不需要交换', en: '1 < 3, no swap needed' },
      action: { type: 'highlight', targets: [0, 1], color: 'success' },
      stats: { comparisons: 13, swaps: 7, accesses: 21 },
    },
    {
      stepId: 37,
      codeLine: 0,
      description: { zh: '比较索引 1 和 2', en: 'Compare index 1 and 2' },
      action: { type: 'compare', targets: [1, 2], color: 'warning' },
      stats: { comparisons: 14, swaps: 7, accesses: 21 },
    },
    {
      stepId: 38,
      codeLine: 2,
      description: { zh: '3 > 2，交换位置', en: '3 > 2, swap them' },
      action: { type: 'swap', targets: [1, 2], color: 'danger' },
      stats: { comparisons: 14, swaps: 7, accesses: 21 },
    },
    {
      stepId: 39,
      codeLine: 3,
      description: { zh: '交换完成，数组变为 [1, 2, 3, 5, 8, 9]', en: 'After swap: [1, 2, 3, 5, 8, 9]' },
      action: { type: 'highlight', targets: [1, 2], color: 'success' },
      stats: { comparisons: 14, swaps: 8, accesses: 23 },
    },
    {
      stepId: 40,
      codeLine: 4,
      description: { zh: '第四轮结束，3 已就位', en: 'Pass 4 done, 3 in place' },
      action: { type: 'mark', targets: [2], color: 'muted' },
      stats: { comparisons: 14, swaps: 8, accesses: 23 },
    },
    {
      stepId: 41,
      codeLine: 0,
      description: { zh: '第五轮：比较索引 0 和 1', en: 'Pass 5: Compare index 0 and 1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 15, swaps: 8, accesses: 24 },
    },
    {
      stepId: 42,
      codeLine: 2,
      description: { zh: '1 < 2，不需要交换', en: '1 < 2, no swap needed' },
      action: { type: 'highlight', targets: [0, 1], color: 'success' },
      stats: { comparisons: 15, swaps: 8, accesses: 25 },
    },
    {
      stepId: 43,
      codeLine: 4,
      description: { zh: '排序完成！所有元素已按升序排列', en: 'Sorted! All elements in ascending order' },
      action: { type: 'mark', targets: [0, 1, 2, 3, 4, 5], color: 'success' },
      stats: { comparisons: 15, swaps: 8, accesses: 25 },
    },
  ],
}

export default bubbleSortPreset
