import type { AnimationScript } from '@/types/animation'

const selectionSortPreset: AnimationScript = {
  algorithm: 'selection_sort',
  complexity: {
    time: { best: 'O(n²)', average: 'O(n²)', worst: 'O(n²)' },
    space: 'O(1)',
  },
  initialState: {
    type: 'array',
    data: [5, 3, 8, 1, 9, 2],
    labels: ['5', '3', '8', '1', '9', '2'],
  },
  steps: [
    {
      stepId: 1,
      codeLine: 0,
      description: { zh: '第 1 轮：假设索引 0 (值=5) 为最小值', en: 'Pass 1: Assume index 0 (val=5) is min' },
      action: { type: 'highlight', targets: [0], color: 'warning' },
      stats: { comparisons: 0, swaps: 0, accesses: 1 },
    },
    {
      stepId: 2,
      codeLine: 4,
      description: { zh: '比较 arr[1]=3 < min=5，更新 min_idx=1', en: 'Compare arr[1]=3 < min=5, update min_idx=1' },
      action: { type: 'compare', targets: [0, 1], color: 'warning' },
      stats: { comparisons: 1, swaps: 0, accesses: 2 },
    },
    {
      stepId: 3,
      codeLine: 5,
      description: { zh: '最小值更新为索引 1 (值=3)', en: 'Min updated to index 1 (val=3)' },
      action: { type: 'highlight', targets: [1], color: 'danger' },
      stats: { comparisons: 1, swaps: 0, accesses: 3 },
    },
    {
      stepId: 4,
      codeLine: 4,
      description: { zh: '比较 arr[2]=8 > min=3，不更新', en: 'Compare arr[2]=8 > min=3, skip' },
      action: { type: 'compare', targets: [1, 2], color: 'muted' },
      stats: { comparisons: 2, swaps: 0, accesses: 4 },
    },
    {
      stepId: 5,
      codeLine: 4,
      description: { zh: '比较 arr[3]=1 < min=3，更新 min_idx=3', en: 'Compare arr[3]=1 < min=3, update min_idx=3' },
      action: { type: 'compare', targets: [1, 3], color: 'warning' },
      stats: { comparisons: 3, swaps: 0, accesses: 5 },
    },
    {
      stepId: 6,
      codeLine: 5,
      description: { zh: '最小值更新为索引 3 (值=1)', en: 'Min updated to index 3 (val=1)' },
      action: { type: 'highlight', targets: [3], color: 'danger' },
      stats: { comparisons: 3, swaps: 0, accesses: 6 },
    },
    {
      stepId: 7,
      codeLine: 4,
      description: { zh: '比较 arr[4]=9 > min=1，不更新', en: 'Compare arr[4]=9 > min=1, skip' },
      action: { type: 'compare', targets: [3, 4], color: 'muted' },
      stats: { comparisons: 4, swaps: 0, accesses: 7 },
    },
    {
      stepId: 8,
      codeLine: 4,
      description: { zh: '比较 arr[5]=2 > min=1，不更新', en: 'Compare arr[5]=2 > min=1, skip' },
      action: { type: 'compare', targets: [3, 5], color: 'muted' },
      stats: { comparisons: 5, swaps: 0, accesses: 8 },
    },
    {
      stepId: 9,
      codeLine: 6,
      description: { zh: '交换 arr[0]=5 和 arr[3]=1', en: 'Swap arr[0]=5 and arr[3]=1' },
      action: { type: 'swap', targets: [0, 3], color: 'danger' },
      stats: { comparisons: 5, swaps: 0, accesses: 8 },
    },
    {
      stepId: 10,
      codeLine: 7,
      description: { zh: '交换完成，数组变为 [1, 3, 8, 5, 9, 2]，索引 0 已就位', en: 'After swap: [1, 3, 8, 5, 9, 2], index 0 placed' },
      action: { type: 'mark', targets: [0], color: 'muted' },
      stats: { comparisons: 5, swaps: 1, accesses: 10 },
    },
    {
      stepId: 11,
      codeLine: 3,
      description: { zh: '第 2 轮：假设索引 1 (值=3) 为最小值', en: 'Pass 2: Assume index 1 (val=3) is min' },
      action: { type: 'highlight', targets: [1], color: 'warning' },
      stats: { comparisons: 5, swaps: 1, accesses: 11 },
    },
    {
      stepId: 12,
      codeLine: 4,
      description: { zh: '比较 arr[2]=8 > min=3，不更新', en: 'Compare arr[2]=8 > min=3, skip' },
      action: { type: 'compare', targets: [1, 2], color: 'muted' },
      stats: { comparisons: 6, swaps: 1, accesses: 12 },
    },
    {
      stepId: 13,
      codeLine: 4,
      description: { zh: '比较 arr[3]=5 > min=3，不更新', en: 'Compare arr[3]=5 > min=3, skip' },
      action: { type: 'compare', targets: [1, 3], color: 'muted' },
      stats: { comparisons: 7, swaps: 1, accesses: 13 },
    },
    {
      stepId: 14,
      codeLine: 4,
      description: { zh: '比较 arr[4]=9 > min=3，不更新', en: 'Compare arr[4]=9 > min=3, skip' },
      action: { type: 'compare', targets: [1, 4], color: 'muted' },
      stats: { comparisons: 8, swaps: 1, accesses: 14 },
    },
    {
      stepId: 15,
      codeLine: 4,
      description: { zh: '比较 arr[5]=2 < min=3，更新 min_idx=5', en: 'Compare arr[5]=2 < min=3, update min_idx=5' },
      action: { type: 'compare', targets: [1, 5], color: 'warning' },
      stats: { comparisons: 9, swaps: 1, accesses: 15 },
    },
    {
      stepId: 16,
      codeLine: 6,
      description: { zh: '交换 arr[1]=3 和 arr[5]=2', en: 'Swap arr[1]=3 and arr[5]=2' },
      action: { type: 'swap', targets: [1, 5], color: 'danger' },
      stats: { comparisons: 9, swaps: 1, accesses: 15 },
    },
    {
      stepId: 17,
      codeLine: 7,
      description: { zh: '交换完成，数组变为 [1, 2, 8, 5, 9, 3]，索引 1 已就位', en: 'After swap: [1, 2, 8, 5, 9, 3], index 1 placed' },
      action: { type: 'mark', targets: [1], color: 'muted' },
      stats: { comparisons: 9, swaps: 2, accesses: 17 },
    },
    {
      stepId: 18,
      codeLine: 3,
      description: { zh: '第 3 轮：假设索引 2 (值=8) 为最小值', en: 'Pass 3: Assume index 2 (val=8) is min' },
      action: { type: 'highlight', targets: [2], color: 'warning' },
      stats: { comparisons: 9, swaps: 2, accesses: 18 },
    },
    {
      stepId: 19,
      codeLine: 4,
      description: { zh: '比较 arr[3]=5 < min=8，更新 min_idx=3', en: 'Compare arr[3]=5 < min=8, update min_idx=3' },
      action: { type: 'compare', targets: [2, 3], color: 'warning' },
      stats: { comparisons: 10, swaps: 2, accesses: 19 },
    },
    {
      stepId: 20,
      codeLine: 4,
      description: { zh: '比较 arr[4]=9 > min=5，不更新', en: 'Compare arr[4]=9 > min=5, skip' },
      action: { type: 'compare', targets: [3, 4], color: 'muted' },
      stats: { comparisons: 11, swaps: 2, accesses: 20 },
    },
    {
      stepId: 21,
      codeLine: 4,
      description: { zh: '比较 arr[5]=3 < min=5，更新 min_idx=5', en: 'Compare arr[5]=3 < min=5, update min_idx=5' },
      action: { type: 'compare', targets: [3, 5], color: 'warning' },
      stats: { comparisons: 12, swaps: 2, accesses: 21 },
    },
    {
      stepId: 22,
      codeLine: 6,
      description: { zh: '交换 arr[2]=8 和 arr[5]=3', en: 'Swap arr[2]=8 and arr[5]=3' },
      action: { type: 'swap', targets: [2, 5], color: 'danger' },
      stats: { comparisons: 12, swaps: 2, accesses: 21 },
    },
    {
      stepId: 23,
      codeLine: 7,
      description: { zh: '交换完成，数组变为 [1, 2, 3, 5, 9, 8]，索引 2 已就位', en: 'After swap: [1, 2, 3, 5, 9, 8], index 2 placed' },
      action: { type: 'mark', targets: [2], color: 'muted' },
      stats: { comparisons: 12, swaps: 3, accesses: 23 },
    },
    {
      stepId: 24,
      codeLine: 3,
      description: { zh: '第 4 轮：假设索引 3 (值=5) 为最小值', en: 'Pass 4: Assume index 3 (val=5) is min' },
      action: { type: 'highlight', targets: [3], color: 'warning' },
      stats: { comparisons: 12, swaps: 3, accesses: 24 },
    },
    {
      stepId: 25,
      codeLine: 4,
      description: { zh: '比较 arr[4]=9 > min=5，不更新', en: 'Compare arr[4]=9 > min=5, skip' },
      action: { type: 'compare', targets: [3, 4], color: 'muted' },
      stats: { comparisons: 13, swaps: 3, accesses: 25 },
    },
    {
      stepId: 26,
      codeLine: 4,
      description: { zh: '比较 arr[5]=8 > min=5，不更新', en: 'Compare arr[5]=8 > min=5, skip' },
      action: { type: 'compare', targets: [3, 5], color: 'muted' },
      stats: { comparisons: 14, swaps: 3, accesses: 26 },
    },
    {
      stepId: 27,
      codeLine: 6,
      description: { zh: '最小值就是索引 3，不需要交换', en: 'Min is index 3, no swap needed' },
      action: { type: 'highlight', targets: [3], color: 'success' },
      stats: { comparisons: 14, swaps: 3, accesses: 26 },
    },
    {
      stepId: 28,
      codeLine: 7,
      description: { zh: '索引 3 已就位', en: 'Index 3 placed' },
      action: { type: 'mark', targets: [3], color: 'muted' },
      stats: { comparisons: 14, swaps: 3, accesses: 27 },
    },
    {
      stepId: 29,
      codeLine: 3,
      description: { zh: '第 5 轮：假设索引 4 (值=9) 为最小值', en: 'Pass 5: Assume index 4 (val=9) is min' },
      action: { type: 'highlight', targets: [4], color: 'warning' },
      stats: { comparisons: 14, swaps: 3, accesses: 28 },
    },
    {
      stepId: 30,
      codeLine: 4,
      description: { zh: '比较 arr[5]=8 < min=9，更新 min_idx=5', en: 'Compare arr[5]=8 < min=9, update min_idx=5' },
      action: { type: 'compare', targets: [4, 5], color: 'warning' },
      stats: { comparisons: 15, swaps: 3, accesses: 29 },
    },
    {
      stepId: 31,
      codeLine: 6,
      description: { zh: '交换 arr[4]=9 和 arr[5]=8', en: 'Swap arr[4]=9 and arr[5]=8' },
      action: { type: 'swap', targets: [4, 5], color: 'danger' },
      stats: { comparisons: 15, swaps: 3, accesses: 29 },
    },
    {
      stepId: 32,
      codeLine: 7,
      description: { zh: '排序完成！数组已按升序排列', en: 'Sorted! Array in ascending order' },
      action: { type: 'mark', targets: [0, 1, 2, 3, 4, 5], color: 'success' },
      stats: { comparisons: 15, swaps: 4, accesses: 31 },
    },
  ],
}

export default selectionSortPreset
